;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
cmderh=cd /d C:\ari
gvim=C:\freeware\vim82-kaoriya-win64\gvim.exe $*
vim=C:\freeware\vim82-kaoriya-win64\vim.exe $*
gomi=mv $* C:\ari\gomi
less=less -M $*
cmdervs=cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:s50H
cmdersp=cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:s50V
cmdertab=cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console
find=C:\PROGRA~1\Git\usr\bin\find.exe $*
ie=C:\PROGRA~1\INTERN~1\iexplore.exe $*
firefox=C:\PROGRA~1\MOZILL~1\firefox.exe $*
chrome=C:\PROGRA~2\Google\Chrome\Application\chrome.exe $*
speedyfox=C:\freeware\speedyfox.exe "/Firefox:default" "/Chrome:Default"
sumatraPDF=C:\PROGRA~1\SumatraPDF\SumatraPDF.exe -invert-colors $*
teraterm=C:\freeware\teratermconf\ssh2login.ttl
vless=C:\freeware\vim82-kaoriya-win64\vim82\macros\less.bat $*
