;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
unalias=alias /d $1
;= vi=vim $*
gvim=C:\freeware\vim82-kaoriya-win64\gvim.exe $*
vim=C:\freeware\vim82-kaoriya-win64\vim.exe $*
gomi=C:\freeware\cmdutils\Recycle.exe $*
less=less -M $*
vless=C:\freeware\vim82-kaoriya-win64\vim82\macros\less.bat $*
find=C:\PROGRA~1\Git\usr\bin\find.exe $*
cmderr=cd /d "%CMDER_ROOT%"
cmderh=cd /d C:\ari
cmdervs=cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:s50H
cmdersp=cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:s50V
cmdertab=cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console
ie=C:\PROGRA~1\INTERN~1\iexplore.exe $*
firefox=C:\PROGRA~1\MOZILL~1\firefox.exe $*
chrome=C:\PROGRA~1\Google\Chrome\Application\chrome.exe $*
edge=start microsoft-edge:https://www.bing.com/  
sumatraPDF=C:\PROGRA~1\SumatraPDF\SumatraPDF.exe -invert-colors $*
teraterm=C:\freeware\teratermconf\ssh2login.ttl
ffmpeg=C:\freeware\ffmpeg-2021-01-24-git-1775688292-full_build\bin\ffmpeg.exe $*
marp=C:\freeware\marp.exe $*
